### ISSUE TITLE
Items in `Transaction.messages` array are always empty objects

### ISSUE THREAD

**Issue by Cyberuben** [goshippo/shippo-javascript-sdk#27]
When querying transactions through the SDK, the parsing of the messages doesn't seem to work properly.

Example response through SDK:
<img width="401" alt="image" src="https://github.com/goshippo/shippo-javascript-sdk/assets/1823121/55f86ba4-e818-4e36-aa9f-075175b97bcb">

Same transaction through Postman:
<img width="571" alt="image" src="https://github.com/goshippo/shippo-javascript-sdk/assets/1823121/cf8f2c01-69a9-4577-82d2-987eddb2c348">

**Comment by shippo-lueders** [comment]
the core issue is that the schema is not really defined, it's just 
```
        messages:
          example: []
          items:
            type: object
          type: array
```

the complexity is that `messages` is likely a shared model, across multiple endpoints (ratings, shipments, transactions) and I'm trying to confirm whether they're really shared or whether there are variances.

in summary - thanks for reporting, trying to figure out the best solve, should have a fix by tomorrow at the latest

**Comment by shippo-lueders** [comment]
https://www.npmjs.com/package/shippo/v/2.2.2 has been published which corrects the message schema
