### ISSUE TITLE
CommercialInvoice Returning Boolean Validation

### ISSUE THREAD

**Issue by richardebrain** [goshippo/shippo-javascript-sdk#31]
I have recently started testing with your api and i was stucked for days on international shipping.

In your code documentation , it says commercialInvoice is a type of string both in documentation and sdk installed but upon testing , i get error that it is a type of boolean from the backend , but on the frontend sdk , it's a type of string and it's even optional..

I have attach several screenshot to explain further more , i am behind on this task for a client ,kindly look into it

![Screenshot 2024-05-11 at 00 09 31](https://github.com/goshippo/shippo-javascript-sdk/assets/65451595/2e1b4b8e-7186-4e48-a372-9fb55af8b589)
![Screenshot 2024-05-10 at 23 58 58](https://github.com/goshippo/shippo-javascript-sdk/assets/65451595/924d1547-ae02-4bc4-bac0-044c38ce344e)
![Screenshot 2024-05-10 at 23 59 08](https://github.com/goshippo/shippo-javascript-sdk/assets/65451595/a0c52842-1b23-42aa-a166-99397f2e1c26)
![Screenshot 2024-05-10 at 23 59 20](https://github.com/goshippo/shippo-javascript-sdk/assets/65451595/391959f0-1f27-4125-804d-529fb4a8540d)

**Comment by shippo-lueders** [comment]
Thanks for reporting, should be fixed by https://www.npmjs.com/package/shippo/v/2.2.4

**Comment by richardebrain** [comment]
Thanks alot , upgraded the current version and it worked ...
