### ISSUE TITLE
Schema Validation Error for Shipment Level

### ISSUE THREAD

**Issue by richardebrain** [goshippo/shippo-javascript-sdk#35]
i created an international shipment during test and i got the error stating this-->
` cause: ZodError: [
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "object",
      "path": [
        "rates",
        0,
        "servicelevel",
        "parent_servicelevel"
      ],
      "message": "Expected string, received object"
    },
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "object",
      "path": [
        "rates",
        1,
        "servicelevel",
        "parent_servicelevel"
      ],
      "message": "Expected string, received object"
    }
  ]` 

but according to returned value ,it returned an object whereas zod is expecting a string.

![Screenshot 2024-05-14 at 09 16 18](https://github.com/goshippo/shippo-javascript-sdk/assets/65451595/eeef68ce-307d-48d9-b104-349d275339d6)

It expects the parentServiceLevel to be a string , but the returned is an object

**Comment by shippo-lueders** [comment]
thanks for reporting!  fixed in https://www.npmjs.com/package/shippo/v/2.2.5

**Comment by richardebrain** [comment]
It's fixed , thanks
