### ISSUE TITLE
Batch Shipment Support

### ISSUE THREAD

**Issue by jfriedr** [goshippo/shippo-javascript-sdk#46]
Getting `SDKValidationError: Response validation failed` when utilizing batch label endpoint:

![image](https://github.com/goshippo/shippo-javascript-sdk/assets/61479880/0e9522ee-f966-4512-b686-b73eb508cfbe)

**Comment by shippo-lueders** [comment]
fixed in https://www.npmjs.com/package/shippo/v/2.2.7
