### ISSUE TITLE
Batch purchase errors

### ISSUE THREAD

**Issue by davlinphd** [goshippo/shippo-javascript-sdk#49]
purchasing a batch successfully POSTS, but returns an error: 

 ⨯ SDKError: Unexpected API response status or content-type: Status 202 Content-Type application/json Body
![Screenshot 2024-05-30 at 9 37 31 AM](https://github.com/goshippo/shippo-javascript-sdk/assets/74466243/3020fa0e-7108-404c-a6c0-652f7c49a396)

**Comment by shippo-lueders** [comment]
fixed in https://www.npmjs.com/package/shippo/v/2.2.8
