### ISSUE TITLE
Lasership Attributes only accepts single attribute

### ISSUE THREAD

**Issue by nathanielmoon** [goshippo/shippo-javascript-sdk#60]
Hello, we appreciate the work you're doing here. I'm raising a compatibility issue.

In the `ShipmentExtra` object, specifically when creating a shipment, the package throws a validation error when multiple `lasershipAttrs` values are provided.

We are currently migrating from the Shippo 2016 API to the Shippo 2018 API and we have upgraded our client package as well.

There is no mention of dropping support for multiple Lasership attributes in the [upgrade doc](https://docs.goshippo.com/docs/api_concepts/api_upgrade_guides/v20161025_to_2018/#shipments).

When running a request to POST `/shipments` via Postman, multiple Lasership values are accepted, indicating that the npm package types are not aligned with the API contract.

We would like to be able to pass multiple Lasership attributes to the API via the npm package. More concretely, the schema should be:

```
export namespace LasershipAttrs$ {
    export const inboundSchema = z.union([z.nativeEnum(LasershipAttrs), z.array(z.nativeEnum(LasershipAttrs))]);
    export const outboundSchema = inboundSchema;
}
```

Thank you!

**Comment by shippo-lueders** [comment]
fixed in https://www.npmjs.com/package/shippo/v/2.3.3, let us know if you run into anything else!

**Comment by nathanielmoon** [comment]
Everything looks good on our end. Thank you!
