### ISSUE TITLE
Missing value in ReturnServiceType

### ISSUE THREAD

**Issue by nathanielmoon** [goshippo/shippo-javascript-sdk#68]
Hello!

We are having an issue where our existing Shippo integration is breaking with the 2.0 upgrade. Currently, we provide a value of `NO_RETURN` to the `return_service_type` field in Shipment Extras. We include this value as part of our integration with Lasership. This field and value were recommended to us by Shippo when we initially built this integration, despite Shippo docs stating that this field is UPS exclusive.

The 2.0 package only provides the UPS fields:

```
export const ReturnServiceType = {
    PrintAndMail: "PRINT_AND_MAIL",
    Attempt1: "ATTEMPT_1",
    Attempt3: "ATTEMPT_3",
    ElectronicLabel: "ELECTRONIC_LABEL",
} as const;
```

We require that `NO_RETURN` also be included in this enum. This is a blocking issue for us. 

Thank you! We appreciate the work that you are doing.

**Comment by shippo-lueders** [comment]
hey @nathanielmoon, fix is in the works but tomorrow is a holiday for us, so probably won't be published until Thursday morning

**Comment by shippo-lueders** [comment]
fixed in https://www.npmjs.com/package/shippo/v/2.4.0, let us know if you have any issues!
