### ISSUE TITLE
Parcel Missing LIST TRANSACTION Response

### ISSUE THREAD

**Issue by nathanielmoon** [goshippo/shippo-javascript-sdk#78]
Hello, we have an issue to raise regarding a missing field.

The [API documentation](https://docs.goshippo.com/shippoapi/public-api/#operation/ListTransactions) indicates that the GET List Transactions endpoint returns a list of Transaction objects, each of which contains a `string` field named `parcel`, which is the object id of a related Parcel object.

We have also verified this to be true when running queries directly against the Shippo API.

However, this SDK does not expose this field. We require the `parcel` field to be exposed via this SDK. We have verified that this is possible by modifying the schemas and transformers in `src/models/components/transaction.ts` to include the `parcel` field.

We are requesting that the SDK be updated to satisfy this requirement. Thank you, we appreciate the support!

**Comment by shippo-lueders** [comment]
this was added earlier today - https://github.com/goshippo/shippo-javascript-sdk/pull/75

and should be available in the latest published artifact - https://www.npmjs.com/package/shippo/v/2.6.1
