### ISSUE TITLE
batches.get lacks support for paging

### ISSUE THREAD

**Issue by rutkowskib** [goshippo/shippo-javascript-sdk#81]
Documentation for `batches.get()` states that  `Batch shipments are displayed 100 at a time. You can iterate through each page using the ?page= query parameter. You can also filter based on batch shipment status, for example, by passing a query param like ?object_results=creation_failed.`.

Unfortunately there is no way to do this, as only parameters that you can pass are batchId and options(they dont allow for passing page either). In Postman I succeeded to fetch more pages, so this is supported in REST API.

**Comment by jfriedr** [comment]
@rutkowskib thanks for bringing this up. We are in the process of getting this addressed and will update this ticket when the SDK is updated with the fix.

**Comment by rkeur7** [comment]
@rutkowskib Sorry for the delay, this should now be resolved with our newest [release of version 2.13.0](https://www.npmjs.com/package/shippo/v/2.13.0?activeTab=versions)
