### ISSUE TITLE
It is not possible to get carriers with services enabled in goshippo 

### ISSUE THREAD

**Issue by vavilondev** [goshippo/shippo-javascript-sdk#82]
When I do get request of carriers or services proving my live token I expect to get services based on my goshippo configuration.
<img width="570" alt="Screenshot 2024-08-01 at 13 00 34" src="https://github.com/user-attachments/assets/bfe2a8ac-8ddf-4ec3-93ca-e5d5af8c567c">
So I expect to get only two services, instead, I get the whole list of all possible services.

**Comment by jfriedr** [comment]
This hide/show service levels within the WebApp does not apply to API calls. If you are looking to provide specific service groups / filter take a look at the following:

https://docs.goshippo.com/shippoapi/public-api/#operation/ListServiceGroups

The endpoint related to this is:

`https://api.goshippo.com/service-groups`
