### ISSUE TITLE
Shippo offers carriers and rates that can't be delivered

### ISSUE THREAD

**Issue by loresclement** [goshippo/shippo-javascript-sdk#96]
Hello,

We discovered quite a huge problem. 
Our users told us that they got a shipment that can't be delivered. Shippo offers carriers and rate even if the carriers location is 1h30 from the address of the shipment.

Is it currently being resolved on your side ? If it's not the case and it's an assumed choice. We will need to use another api

Thank you for your help

**Comment by AdrianCollinsShippo** [comment]
HI @loresclement. I'm sorry to hear you are having difficulties. 
We use GitHub issues to track errors and issues related to our SDK and API.
This sounds like an account issue. Please [submit a support ticket ](https://support.goshippo.com/hc/en-us/requests/new)so can triage your issue and safely share details about the issue you have discovered. 

Thank you.
